### ISSUE TITLE
Modify  auth.livepatch.canonical.com to avoid confusion on enterprise-wide access for livepatch

### ISSUE THREAD

**Issue by g-ramirez** [canonical-web-and-design/www.ubuntu.com#1230]
## Summary

A client would like more information to be present at auth.livepatch.canonical.com.  Specifically, they logged a question regarding regrading how to share their livepatch credentials with everyone at the company.  Their understanding was that the  SSO  token would only active for that user, though our process is that they can share it with it at the company despite it being generated for the initiating user

## Process

Go to https://auth.livepatch.canonical.com/ and request a token.  It will be generating from your personal SSO credentials

## Current and expected result
A token is retrieved, but the client isn't aware that they can share it with everyone in the enterprise.  The client would like the page to say something like, here is your 'enterprise-wide' token, as opposed to token for email.

## Screenshot

![selection_012](https://cloud.githubusercontent.com/assets/9574558/21659386/48c99d66-d27f-11e6-985f-a34b5d3af5bb.png)

**Comment by pmahnke** [comment]
@g-ramirez 

we are confirming if we can tell if we can tweak the message for just Ubuntu Advantage people, but either way, we will update the messaging.

thanks,

Peter

**Comment by g-ramirez** [comment]
Hi Peter,

The client finds that approach to be best as well.

Regards,
Gabe

**Comment by anthonydillon** [comment]
@pmahnke could you please set a priority label.

**Comment by pmahnke** [comment]
@anthonydillon I believe I passed this on to the livepatch team, I can't see if they actioned it, perhaps we can as Maxi?

**Comment by pmahnke** [comment]
closing, as we have passed it onto the store team to work on.
