### ISSUE TITLE
Conjure-up information is not clear.

### ISSUE THREAD

**Issue by chenhaw** [canonical-web-and-design/www.ubuntu.com#2416]
Hi,

I was following the instructions on https://www.ubuntu.com/download/cloud/try-openstack to try out openstack. The instructions given was not clear on the web page as Ubuntu 16.04.3 Server Image will install LXD and LXC under _/usr/bin/lxd_ and _/usr/bin/lxc_. These 2 program won't be used by _conjure up_ as the program that conjure up will use come from _Snap_ under _/snap/bin/lxd_ and _snap/bin/lxc_.

After trigerring _conjure up_ and follow the instructions, on a newly installed server image, it will prompt that LXD is not found and there are 3 instructions to be done.,
1. sudo snap install lxd
2. /snap/bin/lxd init --auto
3. /snap/bin/lxc network create lxdbr0 ipv4.address=auto ipv4.nat=true ipv6.address=none ipv6.nat=false

I suggest the instruction on web page to be change to advice user to perform these 3 instructions first before firing up the _conjure up_ command because if user open up another terminal and run these instructions (some user will need the instructions for reference), the installation will proceed after detected that "_sudo snap install lxd_" has been performed.

This is not a major issue but a small usability and user experience issue as not all user are power user.

Thank you.
---
*Reported from: https://www.ubuntu.com/*

**Comment by pmahnke** [comment]
@evilnick can you help correct this [copy doc](https://docs.google.com/document/d/1TXnoE_RZCgms1K3beJNjzYLNzZEIjfeuNYg_zhkYQTA/edit)?

**Comment by anthonydillon** [comment]
@pmahnke could you add a priority label please.

**Comment by pmahnke** [comment]
@anthonydillon we could ask adam stokes as well, if @evilnick doesn't know.

**Comment by evilnick** [comment]
So, this turns out to be more complicated:

16.04 needs up to date snapd
1804 desktop has no lxd pre-installed, so as long as lxd is installed and configured without IPv6 via either method it is fine
1804 server has the apt version of lxd preinstalled, but not finally configured. LXD init needs to be used before it is run (and no IPv6 used)

**Comment by pmahnke** [comment]
we think https://www.ubuntu.com/openstack/install#workstation-deployment has fixed the issue, closing, reopen if you think it needs more work.
