### ISSUE TITLE
Front page serves over 1 MB of unused CSS

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/www.ubuntu.com#2585]
In Chromium/Chrome:
1\. Go to [www.ubuntu.com](https://www.ubuntu.com/).
2\. Open Developer Tools and focus it.
3\. Type Command/Ctrl+Shift+P to “Run command”.
4\. Type/autocomplete “Show Coverage”.
5\. In the “Coverage” tab, click Reload.

What you see: The page serves over 1 MB of unused CSS, 96% of the style sheet.

![https://www.ubuntu.com/static/css/styles.css?v=ca4298d | CSS | 1198373 | 1152512 96.2%](https://user-images.githubusercontent.com/19801137/34937933-69b83d98-f9de-11e7-83d7-39ba06f3e227.png)

What you should see: The page serves less than, say, 50 KB of unused CSS.

---
*Reported from: https://www.ubuntu.com/*

**Comment by matthewpaulthomas** [comment]
Update:
- www.ubuntu.com/ has 1,166,269 bytes unused of 1,211,143
- The beta site has 321,243 bytes unused of 366,611

That’s a massive improvement (72%), but still nearly 1/3 MB of unused CSS.

**Comment by pmahnke** [comment]
this will be looked at as part of project fuse, closing for now.
