### ISSUE TITLE
Orange Pi information on IoT page

### ISSUE THREAD

**Issue by zprood** [canonical-web-and-design/www.ubuntu.com#2620]
Orange Pi can run Ubuntu Core and snap store, also it is the partner of Canonical too.

Suggest words:
Title: Orange Pi
Content:
It’s an open-source single-board computer. It can run Ubuntu, Ubuntu Core. It uses the AllWinner H3 SoC, and has 1GB DDR3 SDRAM. $9 makes IoT innovations. 

Orange Pi Ubuntu Core 16 image link http://www.orangepi.org/downloadresources/
Orange Pi Logo: http://www.orangepi.org/photo/footer/footer.png
---
*Reported from: https://www.ubuntu.com/internet-of-things*

**Comment by steverydz** [comment]
@zprood Thank you. We will hopefully have some time to look at this soon.

**Comment by anasereijo** [comment]
Hi,

there is a [download Orange Pi page](https://www.ubuntu.com/download/iot/orange-pi-zero). 
If you feel we should mention it on the IoT landing page please reopen this issue. Thank you
