### ISSUE TITLE
No Ubuntu Server team as an option for contributions page

### ISSUE THREAD

**Issue by felimwhiteley** [canonical-web-and-design/www.ubuntu.com#2722]
Howdy,

I was looking to donate but to give props to the server team, alas there is no Ubuntu Server as an option, is it possible to add one. Thank you!

Félim

---
*Reported from: https://www.ubuntu.com/download/desktop/contribute*

**Comment by steverydz** [comment]
@felimwhiteley Thanks for taking the time to file an issue. We will look at this in an upcoming iteration.

**Comment by pmahnke** [comment]
please update copy and layout per the [copy doc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit)

**Comment by anasereijo** [comment]
@solazio design [here](https://github.com/canonical-web-and-design/web-squad/issues/848)

**Comment by anasereijo** [comment]
-  leave 1 column between the contribution scrollers and the Newsletter card 
- please make the newsletter card sticky like we have on blog
- can we make the final contribution an input so people can change it before they pay?
