### ISSUE TITLE
Unclickable “DATASHEET” label with icon

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/www.ubuntu.com#2723]
1\. Go to [the Server Livepatch page](https://www.ubuntu.com/server/livepatch).
2\. Click where it says “DATASHEET”.

![livepatch](https://user-images.githubusercontent.com/19801137/36437824-0052d57c-1660-11e8-9f42-3aa3deeb8a30.png)

What happens: Nothing.

I found this confusing because:
- The card heading barely looks clickable. (The blue is a subtle shade, there’s no underline except on hover, and — even on ubuntu.com — “›” is used more often to indicate hierarchy than to indicate links.)
- A small icon next to text, like the “DATASHEET” element, is commonly used to indicate a download.
- Least importantly, I haven’t found this layout used anywhere else on ubuntu.com. (Other ubuntu.com datasheets are accessed from inline links or orange buttons.)

There are several ways to fix this, including making the link text more obvious, removing the “DATASHEET” label altogether, or making the entire card clickable.

---
*Reported from: https://www.ubuntu.com/server/livepatch*

**Comment by pmahnke** [comment]
this style is depricated, but we will definately try to use bigger hit areas in the future, closing for now.
