### ISSUE TITLE
Create install page for ubuntu server on raspberry pi

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/www.ubuntu.com#2973]
based on https://wiki.ubuntu.com/ARM/RaspberryPi

we should talk to @caldav about how this should work. I am worried all the pages need more updates than they likely are getting.

**Comment by steverydz** [comment]
@frankiegranato Is this issue done? Looks like this page exists: https://www.ubuntu.com/download/iot/raspberry-pi-2-3

**Comment by anasereijo** [comment]
@shivjoshi1996 do you know anything about this?

**Comment by pmahnke** [comment]
done here - https://www.ubuntu.com/download/iot/raspberry-pi-2-3
