### ISSUE TITLE
The install OpenStack on a single machine video is out of date

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/www.ubuntu.com#3074]
We should update the "Watch the conjure-up walkthrough" video on /download/cloud/try-openstack page.
![screenshot-2018-4-26 try openstack with conjure-up download ubuntu 1](https://user-images.githubusercontent.com/1413534/39301756-3c0c3c8c-4948-11e8-8672-d490b429d325.png)

**Comment by anasereijo** [comment]
@anthonydillon who can we ask to update and re-upload the video?

**Comment by anthonydillon** [comment]
Not sure, maybe @pmahnke or marketing?

**Comment by pmahnke** [comment]
please remove the video from https://www.ubuntu.com/openstack/install#workstation-deployment and update the copy doc
