### ISSUE TITLE
The MAAS images are out of date

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/www.ubuntu.com#3077]
The MAAS images on the /download/cloud/build-openstack page are out of date.

**Comment by pmahnke** [comment]
@anthonydillon this page is gone... how is /download/server/provisioning?

**Comment by anthonydillon** [comment]
Yea, they are out of date. Will provide new ones.

**Comment by anasereijo** [comment]
@anthonydillon who can we ask to give us new images?

**Comment by anthonydillon** [comment]
@lilyvidenova or @lyubomir-popov could provide you some up to date screenshots

**Comment by anasereijo** [comment]
hey @lilyvidenova is this something you can help us with? thanks

**Comment by pmahnke** [comment]
@lilyvidenova we could do this tomorrow if you give us the images!

**Comment by lilyvidenova** [comment]
Ah I’ll take a look! Sorry, I didn’t get notified about these earlier!

**Comment by lilyvidenova** [comment]
@anthonydillon @pmahnke not sure [this link](https://drive.google.com/drive/u/1/folders/1ccld1CWmi7vWiT5idDOpurYj00G3uGJ_) will work but I added them to Web team > _Ubuntu > Website > Download > Ubuntu Server > MAAS 2.6 screenshots
