### ISSUE TITLE
Try Kubernetes video is out of date

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/www.ubuntu.com#3079]
The video on the /kubernetes is very out of date.

**Comment by anthonydillon** [comment]
The video is also used: /kubernetes/managed

**Comment by anasereijo** [comment]
@anthonydillon who can we ask to update the videos?

**Comment by anthonydillon** [comment]
@anasereijo maybe marketing or Carmine?

**Comment by anasereijo** [comment]
@caldav is this something you can help us with?

**Comment by pmahnke** [comment]
video has been removed, closing
