### ISSUE TITLE
Reference to Unity's LIM?

### ISSUE THREAD

**Issue by Ads20000** [canonical-web-and-design/www.ubuntu.com#3099]
'interface refinements including individual menu bars in each application window'

Is this referring to the Locally Integrated Menus in Unity, rather than GNOME's CSD? Does this line need updating?

---
*Reported from: https://www.ubuntu.com/desktop*

**Comment by steverydz** [comment]
@Ads20000 Thank you. We'll hopefully have some time to look into this soon.

**Comment by pmahnke** [comment]
@8none1 is this true?

**Comment by 8none1** [comment]
Yes, good spot. That can be removed.

**Comment by pmahnke** [comment]
Please remove that phrase from the page - see [copy doc](https://docs.google.com/document/d/1ZhMkLlkXcimHTIe1taXy24vbbR9pBkZd49H2sJqeQH0/edit#)
