### ISSUE TITLE
flavors download page links to deprecated derivative page

### ISSUE THREAD

**Issue by wxl** [canonical-web-and-design/www.ubuntu.com#3226]
There's a [flavor downloads page][1], which you can get to from the main download page that links to "A complete list of known flavours, editions and customizations is maintained on the Ubuntu Wiki Derivatives Team page." While all that's well and good, it links to a [team][2] which appears to be deprecated.

Here's the evidence:
 1. It mentions "[official editions][3]" that have been long unsupported. 
 2. It has an [IRC channel][4] (#ubuntu-derativeteam) that is not registered. 
 3. Its [mailing list][5] does not exist. 
 4. The [Launchpad team][6] has members who have been pending since 200**8**.

I think it might be better to either remove the link entirely or to link to the [Ubuntu Flavors][7] page on the wiki.

[1]: https://www.ubuntu.com/download/flavours
[2]: https://wiki.ubuntu.com/DerivativeTeam/Derivatives
[3]: https://wiki.ubuntu.com/DerivativeTeam/Derivatives#Official_editions
[4]: https://wiki.ubuntu.com/DerivativeTeam/GettingInvolved#Contacts
[5]: https://lists.ubuntu.com/mailman/listinfo/ubuntu-derivatives
[6]: https://launchpad.net/~derivativeteam
[7]: https://wiki.ubuntu.com/UbuntuFlavors

**Comment by steverydz** [comment]
Thank you. We will hopefully have some time to look at this soon.

**Comment by wxl** [comment]
When do we expect this to go live?

**Comment by anthonydillon** [comment]
@wxl this is now live.

**Comment by wxl** [comment]
Thank you @anthonydillon !
