### ISSUE TITLE
“Plans and pricing” looks like it stops after the first button

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/www.ubuntu.com#3247]
In a browser with a viewport between about 600 and 750 pixels high — for example, a full-screen browser window on a 1200×800 display:

1\. Go to [ubuntu.com/support/plans-and-pricing](https://www.ubuntu.com/support/plans-and-pricing).

What you see: Apparently, the whole page.

![plans and pricing 1280x800 small](https://user-images.githubusercontent.com/19801137/40668876-812ac23c-635d-11e8-9ce3-f72250a39078.png)

What you should see: It should be obvious that the page scrolls.

Some possible ways to improve this, most likely first:

- Rearrange the page so there isn’t an empty trough from the 600-pixel to the 750-pixel mark. For example, add an illustration that spans the trough.

   ![plans and pricing cropped](https://user-images.githubusercontent.com/19801137/40669254-6c5eba9c-635e-11e8-9766-1453e9204016.png)

- Remove the grey background, since (at this point at least) it looks like it might be the start of a footer.

- Add a table of contents to the page (especially since it’s really long).

- Move “Get in touch” lower on the page, after the more specific buttons and links.

**Comment by anasereijo** [comment]
this page has been updated recently so I will close this issue
