### ISSUE TITLE
Some pages are indexed multiple times with utm_* parameter URLs

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/www.ubuntu.com#3335]
1\. From any page on ubuntu.com, [search for “infographic”](https://www.ubuntu.com/search?q=infographic).

What happens: The first two results are pages that do not contain the word “infographic” at all:
- [Get Ubuntu | Download | Ubuntu](http://www.ubuntu.com/download?utm_source=Infographic&utm_medium=Infographic&utm_campaign=FY17Q1_Ubuntu_Infographic&)
- [The leading operating system for PCs, IoT devices, servers ...](http://www.ubuntu.com/?utm_source=Infographic&utm_medium=Link&utm_campaign=FY16Q%24_Ubuntu_Infgraphic&)

What should happen: These two pages should not be returned as results.

The pages are returned apparently because they include “infographic” in their URLs:
- …`?utm_source=Infographic&utm_medium=Infographic&utm_campaign=FY17Q1_Ubuntu_Infographic&`
- …`?utm_source=Infographic&utm_medium=Link&utm_campaign=FY16Q%24_Ubuntu_Infgraphic&` [sic]

But the same two pages are indexed separately without these URL parameters, as shown in these example searches:
   - “[get ubuntu downloads](https://www.ubuntu.com/search?q=get+ubuntu+downloads)” (first result)
   - “[the leading operating system](https://www.ubuntu.com/search?q=the+leading+operating+system)” (first result)

So, probably the indexer is following these links from somewhere else on ubuntu.com, and not realizing that they return exactly the same pages as the equivalent URLs without any parameters.

Besides causing irrelevant search results, this indexing is probably distorting the statistics of how often people follow those links in their original location.

I can think of three ways to fix it, though maybe there are others:
- Exclude any URL containing `?` from being indexed
- Exclude any URL containing `?utm_` or `&utm_` from being indexed
- Include `<link rel="canonical"`… on any page containing `?utm_` or `&utm_` in its URL.

---
*Reported from: https://www.ubuntu.com/search?q=infographic*

**Comment by pmahnke** [comment]
are you still seeing this? I don't get these results now.

**Comment by pmahnke** [comment]
@matthewpaulthomas looked again, don't see these results so closing... reopen if I am missing something

**Comment by matthewpaulthomas** [comment]
Verified, thanks. There are still [two URLs in the search index that contain `utm_source`](https://www.ubuntu.com/search?q=utm_source), which isn’t ideal, but at least neither of them are duplicates.
