### ISSUE TITLE
buy.ubuntu.com: Changing quantity reloads the page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/www.ubuntu.com#3573]
(Sorry if this is on the wrong project: buy.ubuntu.com has no “Report a bug” link in its footer.)

1\. Go to [buy.ubuntu.com](https://buy.ubuntu.com/).
2\. Click “For Virtual Machines”, “For Servers”, or “For Desktops”.
3\. Click any “Add to Cart” button.
4\. On the shopping cart page, click “+” or (once you’ve done that) “–”.

What happens: The page reloads with the new quantity and subtotal.

What should happen: If JS is available, the quantity and subtotal updates without reloading the page.

---
*Reported from: https://www.ubuntu.com/*

**Comment by cjohnston1158** [comment]
This may be due to enforced minimums, however, I don't know how much control we have over it. @WillMoggridge

**Comment by pmahnke** [comment]
we don't control how shopify works, cannot fix
