### ISSUE TITLE
Error downloading ubuntu 16.04 ppc

### ISSUE THREAD

**Issue by sysadminfbf** [canonical-web-and-design/www.ubuntu.com#3746]
Found a dead link while trying to download ubuntu 16.04 for POWER

Here's the message I get
The requested URL /releases/16.04.2/release/ was not found on this server.

Thanks
---
*Reported from: https://www.ubuntu.com/download/server/power*

**Comment by steverydz** [comment]
Thanks for filing an issue. We'll hopefully have a fix for this soon.
