### ISSUE TITLE
Rename www.ubuntu.com to ubuntu.com

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/www.ubuntu.com#3820]
Redirect www.ubuntu.com to ubuntu.com, and consider carefully any ramifications.

**Comment by anasereijo** [comment]
@nottrobin is this still relevant?

**Comment by nottrobin** [comment]
Very. Hopefully to start very soon. Although I'm not sure why it doesn't seem to be in an epic... let me try to sort that out.

**Comment by nottrobin** [comment]
Yep. This epic should hopefully start very soon. I'm just checking with IS if we can progress with it.

**Comment by tbille** [comment]
@nottrobin to move to another epic

**Comment by anasereijo** [comment]
@nottrobin is there an epic for this?

**Comment by pmahnke** [comment]
@nottrobin or @b-m-f can you move this to your django2 www migration epic

**Comment by pmahnke** [comment]
Issue moved to [canonical-web-and-design/base-squad #552](https://github.com/canonical-web-and-design/base-squad/issues/552) via [**ZenHub**](https://www.zenhub.com/)
