### ISSUE TITLE
IoT “app store” screenshot is an unstyled “Acme_corp”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/www.ubuntu.com#3901]
1\. Go to [“Ubuntu for the Internet of Things”](https://www.ubuntu.com/internet-of-things).
2\. Scroll to the app store screenshot.

What you see: A mockup of an “Acme_corp” store, with plain white text on a black background.

What you should see: Something more realistic.

One way of fixing this would be to use a screenshot of the real [limenet.snapcraft.io](https://limenet.snapcraft.io/). Lime Micro already has [a screenshot of this site on their own site](https://limemicro.com/initiatives/limenet/), and [our “App store” page](https://www.ubuntu.com/internet-of-things/appstore) includes the Lime Microsystems logo in the “Used by” section.

Another way of fixing this would be to change the mockup to include a logo and colour scheme for an imaginary IoT vendor.

---
*Reported from: https://www.ubuntu.com/internet-of-things/appstore*

**Comment by anasereijo** [comment]
@therealjuan are you aware of any nice brand store we can use?

**Comment by pmahnke** [comment]
@therealjuan do you have a better image?
