### ISSUE TITLE
JupyterHub page on Ubuntu.com not rendering properly from my safari browser  

### ISSUE THREAD

**Issue by campbieil** [canonical-web-and-design/www.ubuntu.com#3919]
JupyterHub page on Ubuntu.com not rendering properly from my safari browser 

![jupyterhub](https://user-images.githubusercontent.com/230348/44356833-63c33a80-a4a8-11e8-95aa-6b62e00c8ff4.png)

---
*Reported from: https://www.ubuntu.com/ai/features*

**Comment by anasereijo** [comment]
I just tested and seems to work fine (safari).
If this is still an issue please reopen.
