### ISSUE TITLE
Opening the menu breaks the back button

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/www.ubuntu.com#3920]
## Summary

If you click to open one of the top level menu links, Enterprise, Developer, Community, etc. the back button does not work as expected.

## Process

Click one of the top menu items then hit the back button. You'll see the url change but the menu does not close.

Clicking to open and close a number of menu's then hitting the back button updates the url multiple times but the last opened menu stays active.

## Current and expected result

The menu doesn't close. It should

**Comment by hatched** [comment]
This appears to be because there are no event handlers in the navigation.js file for the popstate event.

**Comment by anthonydillon** [comment]
Yes this is an important issue we should address as soon as we can.

**Comment by anthonydillon** [comment]
It's only a small task

**Comment by anasereijo** [comment]
@dev please estimate this
