### ISSUE TITLE
Update livepatch datasheet

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/www.ubuntu.com#3926]
Livepatch datasheet should be updated to reflect that livepatch isn't available to only 14.04 and 16.04

https://assets.ubuntu.com/v1/ac3aa269-DS_Canonical_Livepatch_Service_screen-AW_08.17.pdf

---
*Reported from: https://www.ubuntu.com/server/livepatch*

**Comment by pmahnke** [comment]
@caldav or @Khutch25 for you

**Comment by pmahnke** [comment]
emailed kelly and david on 8 May 2019

**Comment by pmahnke** [comment]
this has been updated - https://assets.ubuntu.com/v1/ef19ede0-Datasheet_Livepatch_AW_Web_30.07.18.pdf
