### ISSUE TITLE
Update marketo's u.c landing page template

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/www.ubuntu.com#4031]
update to the new navigation

<img width="1671" alt="screen shot 2018-09-10 at 10 11 35" src="https://user-images.githubusercontent.com/36884067/45288160-ea849980-b4e1-11e8-98d6-378eabc58ee0.png">

mobile nav isn't loading
<img width="987" alt="screen shot 2018-09-11 at 10 20 52" src="https://user-images.githubusercontent.com/36884067/45350962-ec675f00-b5ac-11e8-9bef-5f09f863402f.png">

---
*Reported from: https://pages.ubuntu.com/kubernetes-month.html?_ga=2.51888937.1046260181.1536503512-771905585.1528881412*

**Comment by pmahnke** [comment]
that is marketing's marketo page.

it would require a project to update their template, which we should do.

**Comment by pmahnke** [comment]
I have fixed this... global nav is still coming

![image](https://user-images.githubusercontent.com/441217/58247055-a1fbcc00-7d50-11e9-8571-ad7190f166b9.png)
