### ISSUE TITLE
Old Navigation on Openstack ebook page 

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/www.ubuntu.com#4032]
please update to the new nav.

<img width="1450" alt="screen shot 2018-09-10 at 10 18 39" src="https://user-images.githubusercontent.com/36884067/45288644-13f1f500-b4e3-11e8-8b6b-1c0fc2a16df0.png">

---
*Reported from: https://pages.ubuntu.com/stuckstack_download.html?utm_source=website

**Comment by pmahnke** [comment]
dup of #4031, closing
