### ISSUE TITLE
Make global nav work responsively

### ISSUE THREAD

**Issue by Greggless** [canonical-web-and-design/www.ubuntu.com#4462]
Make global work nav behave nicer @<875px

![image](https://user-images.githubusercontent.com/23459065/49365426-b1be2000-f6de-11e8-91c8-d2f6583e1b4f.png)

![image](https://user-images.githubusercontent.com/23459065/49363858-b254b780-f6da-11e8-942c-d39a2ff4080c.png)

![image](https://user-images.githubusercontent.com/23459065/49363879-c00a3d00-f6da-11e8-873b-4abd9a7d070e.png)

**Comment by pmahnke** [comment]
looks like it was fixed?
