### ISSUE TITLE
[epic] Create ai/consulting page

### ISSUE THREAD

**Issue by Greggless** [canonical-web-and-design/www.ubuntu.com#4535]
# Build according to [Copy doc](https://docs.google.com/document/d/19Mx1zRJKqH2hz5kRF_oDsgyFUw67FgJvW4I_OGda-wk/edit)

**Comment by anthonydillon** [comment]
What is going on with this task? I do not see its epic in the backlog.

**Comment by Greggless** [comment]
- ⚠️ Copy isn't ready
- 📔 I made it its own epic
- 📉  Added it to the backlog

**Comment by pmahnke** [comment]
old, closing
