### ISSUE TITLE
Search finds forum posts

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/www.ubuntu.com#4563]
I'm looking for an article about 'snap refresh' so here's the process:-

Visit https://docs.snapcraft.io/
Type 'refresh' in the search box - resulting in https://www.ubuntu.com/search?siteSearch=docs.snapcraft.io&q=refresh

The first two hits (and probably many more) are *not* documentation. They are random forum posts which are *not* tagged as docs/wiki posts, but just conversations. 

![image](https://user-images.githubusercontent.com/1841272/51108699-ebf50400-17ea-11e9-8257-6271d35d3fec.png)

https://docs.snapcraft.io/3081 
https://docs.snapcraft.io/140/21

This is not useful search results. It should *only* bring up posts from the forum which are tagged as docs.

---
*Reported from: https://www.ubuntu.com/search?q=refresh

**Comment by pmahnke** [comment]
@popey I think this was recently fixed, so closing

thanks for reporting it

![image](https://user-images.githubusercontent.com/441217/58163739-698abe00-7c7c-11e9-9587-6bb2f7efebf5.png)
