### ISSUE TITLE
/legal/ubuntu-advantage-service-description - move contents table to the left

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/www.ubuntu.com#4564]
I think we should move Contents table to the left-hand side to keep consistency with other pages (for example docs) 
![screenshot 2019-01-14 at 14 17 11](https://user-images.githubusercontent.com/36884067/51118192-aabf1d00-1807-11e9-8a30-1f0ce6d085f4.png)

Maybe we should look at this page as a whole. It's very long and hard to read. Perhaps we can use the same system we have for docs? I am happy to sit with a developer and go through this together.

---
*Reported from: https://www.ubuntu.com/legal/ubuntu-advantage-service-description*

**Comment by pmahnke** [comment]
@anasereijo let's talk when you are back, but docs use that right col toc for in-page links as well.

**Comment by pmahnke** [comment]
too painful to do right now, closing.
