### ISSUE TITLE
Mailing list admin pages are returned in search results

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/www.ubuntu.com#4771]
Mailman “Administrator Authentication” pages show up in ubuntu.com search results.

This is easiest to reproduce by [searching for “Administrator Authentication”](https://www.ubuntu.com/search?q=administrator+authentication). But I encountered this problem when [searching for “big data”](https://www.ubuntu.com/search?q=big+data), which returned [“Bigdata Administrator Authentication”](https://lists.ubuntu.com/mailman/admin/bigdata) as the 5th result.

Probably the most effective way to fix this would be to set `<meta name="robots" content="noindex">` for those pages within Mailman itself. (Maybe this is even appropriate for upstream Mailman.) Otherwise, I guess they could be excluded from within the ubuntu.com search config.

**Comment by pmahnke** [comment]
@nottrobin can we exclude lists from search results

**Comment by nottrobin** [comment]
I'm not sure I agree that this is actually a problem. The page itself is perfectly fine to be public, and in fact often a difficult page to find when one is looking for it, so it showing up in search results might actually be helpful.

I agree that if these administrator pages were showing up really high, like the first result, for search terms that should lead to other places that would be a concern, but it showing up 5th doesn't seem too problematic to me. Also when I looked, "Bigdata Administrator Authentication" wasn't on the first page of https://www.ubuntu.com/search?q=big+data.

I think it might be reasonable to ask the Mailman project to add `noindex` to Administrator pages and see what they think of the idea, but by and large I'm not sure we should set a precedent of tailoring the search behaviour in cases like this.

Assuming my judgement here can be acceptable, I'm gonna close this for now. But feel free to continue discussion.

**Comment by matthewpaulthomas** [comment]
> The page itself is perfectly fine to be public

I agree it’s not a security vulnerability or privacy breach or anything like that. But I do think visitors would perceive it as mistaken or unprofessional. It’s a bit like finding a “Wordpress login” link on a company’s site: common, not a security issue, and handy for staff who do want to admin the site, but something that grown-up sites don’t do.

> Also when I looked, "Bigdata Administrator Authentication" wasn't on the first page

Those results have shuffled around, but here are three current realistic examples of searches with list admin stuff on the first results page: [ubuntu reviews](https://www.ubuntu.com/search?q=ubuntu+reviews), [security authentication](https://www.ubuntu.com/search?q=security+authentication), [mailman administration](https://www.ubuntu.com/search?q=mailman+administration).
