### ISSUE TITLE
kubernetes support lifetime graph goes in the opposite direction to the others

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/www.ubuntu.com#4910]
Hello, most of the support lifetime graphs on the release cycle page put newer releases at the top of the graph, and older releases at the bottom. The kubernetes support lifetime graph has flipped this around and puts the newest release at the bottom.

Thanks

---
*Reported from: https://www.ubuntu.com/about/release-cycle*

**Comment by pmahnke** [comment]
@setharnold ironically I just noticed this on the copy doc... will fix soon

**Comment by pmahnke** [comment]
@setharnold this was fixed in another PR... so closing

thanks!

![image](https://user-images.githubusercontent.com/441217/56686832-cc645600-66cc-11e9-91a6-6457b9894ae8.png)
