### ISSUE TITLE
Set up proxy for CVEs

### ISSUE THREAD

**Issue by joemcmanus** [canonical-web-and-design/www.ubuntu.com#4937]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary
 Can we set up a url based proxy for
> www.ubuntu.com/security/cve  to serve the pages under :
> https://people.canonical.com/~ubuntu-security/cve/ ?  Or if that is
> not possible can you mirror the files in to appear under that url?
> 
> If this is not the right team to ask, my apologies. If you could point
> me in the right direction that would be awesome!
## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
@joemcmanus we should setup a meeting in Lyon with you, me and Thibaut.

u.c isn't really meant to just host a bunch of stuff without a LOT of thought and care about how it works for users in terms of navigation, look and feel, usability, search, etc.  It is a special site that is highly currated by my team, marketing, Mark, etc.  proxying things in, without proper consideration is a mistake.

I spoke to to Thibaut, we think it would be better to integrate this information into the USN site and then, perhaps look at adding that to u.c.

Closing this issue for now.
