### ISSUE TITLE
'OpenStack Security' takeover - design

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/www.ubuntu.com#4938]

**Comment by SirSamTumless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Openstack security Whitepaper](https://trello.com/c/IMLWasZ6/237-openstack-security-whitepaper)

**Comment by anasereijo** [comment]
Hi @SirSamTumless I'm not sure what is that Trello link for, but I can't open it. I think you may need to invite me to the board?

**Comment by anasereijo** [comment]
DESKTOP

![FINAL - Takeover-large-screen](https://user-images.githubusercontent.com/36884067/56570104-376d3a00-65b2-11e9-9f39-5876cbf9abc5.jpg)


MOBILE

![Takeover-small-screen](https://user-images.githubusercontent.com/36884067/56570109-3a682a80-65b2-11e9-8973-44c6245dcd24.jpg)
