### ISSUE TITLE
'OpenStack Security' takeover - build

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/www.ubuntu.com#4940]

**Comment by anasereijo** [comment]
@solazio this is ready to be built :)

- Please be aware that the copy used on the designs isn't the final one. Check the [copydoc](https://docs.google.com/document/d/1Qg3sgDrvH9w_sgJpb2fp5lyOA5R-xhGZM3aKcyuQT68/edit#)
- [Designs](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/4938)
- [Illustration](https://assets.ubuntu.com/v1/2c91289c-openstack-cloud.svg)
   - desktop: 313px wide
   - mobile: 261px wide
- Background: 
   - gradient: `background-image: linear-gradient(44deg, #171717 0%, #181818 9%, #262626 34%, #2D2D2D 67%, #383838 88%, #2E2E2E 100%, #393939 100%);`
   - [suru left](https://assets.ubuntu.com/v1/e6a2c401-suru-left.svg) (hide it on mobile)
   - [suru right](https://assets.ubuntu.com/v1/a9dab044-suru-right.svg) (hide it on mobile)

**Comment by SirSamTumless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Openstack security Webinar](https://trello.com/c/2tMMG7Cc/238-openstack-security-webinar)

**Comment by SirSamTumless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Openstack security Whitepaper](https://trello.com/c/IMLWasZ6/237-openstack-security-whitepaper)
