### ISSUE TITLE
[Hiri] landing page - design

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/www.ubuntu.com#4941]
Based on [this brief](https://docs.google.com/document/d/1nVAMTjUPiZwxoH9ysh06fbGACcPUNVu0QhYusaOKfIA/edit)

**Comment by anasereijo** [comment]
desktop

![hiri-landingpage](https://user-images.githubusercontent.com/36884067/56643039-b5901600-6670-11e9-9074-093511cc5126.jpg)
