### ISSUE TITLE
[Hiri] landing page - build

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/www.ubuntu.com#4943]
Based on [this brief](https://docs.google.com/document/d/1nVAMTjUPiZwxoH9ysh06fbGACcPUNVu0QhYusaOKfIA/edit)

**Comment by anasereijo** [comment]
this is ready to be built:

### Banner

- [copydoc](https://docs.google.com/document/d/1B5ek9Mfina_c9rrnuUS9kgr1kzo-jqlcqoibIvEV9oU/edit)

- [design](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/4941)

- font `h1`

- gradient [background-image: linear-gradient(181deg, #106363 12%, #083333 100%);](url)

- [logo](https://assets.ubuntu.com/v1/b8255328-download.png) 192px wide (hide it on small screens)

### Content

please follow the copydoc for text and the usual style we have on landing pages.
