### ISSUE TITLE
[Takeover + landing] MAAS Automated Hardware Testing WP - Design

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/www.ubuntu.com#5006]
Brief [https://docs.google.com/document/d/1xyNrWYsYcvux_gYtoWw39XD9cP4QmiAYJnDlLuV8CvE/edit?ts=5cab9e6f#heading=h.gjdgxs](https://docs.google.com/document/d/1xyNrWYsYcvux_gYtoWw39XD9cP4QmiAYJnDlLuV8CvE/edit?ts=5cab9e6f#)

**Comment by pmahnke** [comment]
## Build the data centre of the future
#### Learn how to provision and manage bare metal servers like a cloud with MAAS

[ Download the whitepaper ]()

**Comment by anasereijo** [comment]
@spencerbygraves see below 2 options (FYI: I checked with Wayne which logo version to use)
please let me know your thoughts :)

### MAAS logo 3 column wide

![FINAL - Takeover-large-screen Copy 5](https://user-images.githubusercontent.com/36884067/57087903-08b13b00-6cf9-11e9-9fcf-a7bd441f0f41.jpg)


### MAAS logo 4 column wide
![FINAL - Takeover-large-screen Copy 6](https://user-images.githubusercontent.com/36884067/57087926-0fd84900-6cf9-11e9-8df5-e1c5404ffc38.jpg)

**Comment by spencerbygraves** [comment]
@anasereijo I prefer the larger logo version. Thanks.

**Comment by anasereijo** [comment]
![FINAL - Takeover-large-screen Copy 6](https://user-images.githubusercontent.com/36884067/57126536-2deb8b00-6d85-11e9-9fc4-eabcdb159bca.jpg)
![Takeover-small-screen](https://user-images.githubusercontent.com/36884067/57126537-2e842180-6d85-11e9-8b31-32f2293359e7.jpg)
