### ISSUE TITLE
[Takeover + landing] MAAS Automated Hardware Testing WP - UX

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/www.ubuntu.com#5007]
[Brief](https://docs.google.com/document/d/1xyNrWYsYcvux_gYtoWw39XD9cP4QmiAYJnDlLuV8CvE/edit?ts=5cab9e6f#)

[Takeover](https://docs.google.com/document/d/1SfZKopMr0ZXnxT5h1cEEebCysp6Carf9GSPzkL51c8E/edit)

**Comment by pmahnke** [comment]
# Build the data centre of the future
#### Learn how to provision and manage bare metal servers like a cloud with MAAS

[ Download the whitepaper ]()
