### ISSUE TITLE
[Webinar: takeover + lp] Transformation of the DevOps Journey in IoT - Build

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/www.ubuntu.com#5023]
brief: https://docs.google.com/document/d/1P7tOkSQZwh0vcHUMp2X2wPvGUQORktNRLjPXhrTakF8/edit#

**Comment by anasereijo** [comment]
@solazio this is ready to be built.

- [check designs](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5021) (please be aware that the copy might not be the final one - check [copydoc](https://docs.google.com/document/d/1P7tOkSQZwh0vcHUMp2X2wPvGUQORktNRLjPXhrTakF8/edit#))
- [illustration](https://assets.ubuntu.com/v1/f3d518db-devops-iot.svg) (on mobile make it 300px wide)
- gradient: `background-image: linear-gradient(134deg, #111111 0%, #212121 100%);`
- [suru left ](https://assets.ubuntu.com/v1/69d263b9-left.svg)(hide it on mobile)
- [suru right ](https://assets.ubuntu.com/v1/c6f9e52d-right.svg)(hide it on mobile)

**Comment by solazio** [comment]
@anasereijo do I use the same design for both takeover and landing page?

**Comment by anasereijo** [comment]
@solazio use the same gradient and no illustration
