### ISSUE TITLE
[cloud-init] design takeover + landing page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/www.ubuntu.com#5024]
[brief](https://docs.google.com/document/d/1sPg4mSovCx1J0DpvBo818ulCFCgPhTRxSz8BRFF62w8/edit)

**Comment by anasereijo** [comment]
![FINAL - Takeover-large-screen Copy 3](https://user-images.githubusercontent.com/36884067/57011248-a6711100-6bf8-11e9-809f-2ab33c53b131.jpg)
![Takeover-small-screen](https://user-images.githubusercontent.com/36884067/57011249-a6711100-6bf8-11e9-88aa-e8ec3d7cd3e2.jpg)
