### ISSUE TITLE
[cloud-init] build takeover + landing page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/www.ubuntu.com#5026]
[brief](https://docs.google.com/document/d/1sPg4mSovCx1J0DpvBo818ulCFCgPhTRxSz8BRFF62w8/edit)

**Comment by anasereijo** [comment]
## Takeover

- [designs](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5024)
- gradient (same gradient on mobile too): `transform: rotate(180deg);
background-image: linear-gradient(34deg, #E95420 0%, #C44631 6%, #A33940 12%, #8B304A 18%, #7C2B51 24%, #772953 29%, #55163B 51%, #370626 75%, #2C001E 89%);`
- [suru](https://assets.ubuntu.com/v1/dff57ac6-suru-right.png) (hide them on small screens)
- [illustration](https://assets.ubuntu.com/v1/28e89608-cloud-init.svg)

## Landing page
- same gradient
- do not use suru here
- same illustration (hide it on mobile)

**Comment by anasereijo** [comment]
@solazio this is ready to be built. please make this a priority. thank you
