### ISSUE TITLE
  [Iot DevOps WP] build takeover + landing page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/www.ubuntu.com#5031]
[brief](https://docs.google.com/document/d/1imuKA06xisHD5RURurRhiJuoVeQ3qGojpOVX6odPxR0/edit?ts=5caa27c6)

**Comment by pmahnke** [comment]
# Transform the IoT DevOps journey
#### Using Ubuntu Core and snaps to accelerate the Linux development cycle

[Download the whitepaper]()

**Comment by anasereijo** [comment]
@solazio use the same design as the [previous takeover](https://github.com/canonical-web-and-design/web-squad/issues/1112)

**Comment by anasereijo** [comment]
@solazio this is ready to be built.
