### ISSUE TITLE
Search relevancy doesn't include Juju version number when returning results 

### ISSUE THREAD

**Issue by timClicks** [canonical-web-and-design/www.ubuntu.com#5047]
## Summary

The search functionality for docs.jujucharms.com is provided by www.ubuntu.com, but there is no ability for the user to specify which version of Juju, e.g.

    https://www.ubuntu.com/search?q=actions&domain=docs.jujucharms.com

The relevancy metrics are not weighted towards the current version of the Juju docs that the user is currently looking through. That is, I could be reading the 2.5 documentation, but be given search results for 2.0 or earlier that rank very highly. 

## Process

- Visit https://docs.jujucharms.com/2.5/en
- Search for something using the dialogue box in the top-right corner 

## Current and expected result

The search results include documentation from versions earlier than 2.5. To be most helpful, obsolete versions would be filtered away.

## Screenshot

In this screenshot, the user has searched for "actions". A result from 2.0 appears as the second result, even though that version is very old. 

![search](https://user-images.githubusercontent.com/27889/56871577-1609c380-6a74-11e9-80ac-06cdc733e319.png)

**Comment by nottrobin** [comment]
Hi @timClicks, thanks for filing this.

This is a known issue, but it will cease to be an issue very soon.

This documentation system will be updated very soon so that docs.jujucharms.com serves only 1 canonical version of documentation, pulled from dicsourse.jujucharms.com ([explained here](https://discourse.jujucharms.com/t/documentation-migrated-to-discourse/1274)). At that point, only those "latest" documentation pages will appear in search results - and these documentation pages should include inline caveats to explain differences between versions.

The old versioned documentation will still be available at https://old-docs.jujucharms.com for the time being, but those pages will not be included in search results.

**Comment by nottrobin** [comment]
I'll close this now, as it should be naturally fixed within the fortnight.

**Comment by timClicks** [comment]
Unfortunately, this is still a problem. A [search for "actions"](https://ubuntu.com/search?q=actions&domain=docs.jujucharms.com) still brings up results from the 2.0 and 2.4 series on the front page.

**Comment by nottrobin** [comment]
Yes, true, Google's natural re-indexing clearly takes longer than I thought. There are some results for old versions of docs, but not that many. When I did the [search for "actions"](https://ubuntu.com/search?q=actions) just now - the first old doc was the 6th result. The first page had 2:

https://docs.jujucharms.com/2.0/authors-relations-in-depth
https://docs.jujucharms.com/2.1/users-creating

And the 2nd page had 4:

https://docs.jujucharms.com/2.0/charms-working-with-units
https://docs.jujucharms.com/2.1/en/howto-updateseries
https://docs.jujucharms.com/1.25/en/howto-vagrant-workflow
https://docs.jujucharms.com/2.0/help-joyent

If you click through to any of these pages, you will see a clear banner explaining that these are old documents. I don't think the experience here is unacceptable, and these results are clearly dropping off as Google re-crawls these URLs.

There is no way to ask Google to recrawl a site in bulk - see https://support.google.com/webmasters/answer/6065812?hl=en. We can submit a sitemap, but that is only additive - it can ask Google to reindex pages, it won't make Google forget about URLs not in the sitemap.

We can ask Google to manually crawl individual URLs, and I've done that for the 6 URLs above, and they should disappear from the search results soon. 

However, while old documentation pages are not in the top 3 results for a search term, I think it's more trouble than it's worth to go through and manually ask Google to recrawl all the old pages. If there are common search terms that return old documentation pages in the top 3 results, I think for those URLs it would be worth manually re-indexing. Please let me know if you find such cases.

**Comment by nottrobin** [comment]
Okay I've now gone through the 48 URLs in [this search](https://www.google.com/search?q=site:docs.jujucharms.com/1.*+OR+site:docs.jujucharms.com/2.*+OR+site:docs.jujucharms.com/devel) (at the time of writing) and requested Google forget about them through the [Remove URLs tool](https://www.google.com/webmasters/tools/url-removal?siteUrl=https://docs.jujucharms.com/).
