### ISSUE TITLE
Update release chart on /server page

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/www.ubuntu.com#5058]
The release chart doesn't have the ESM support additions to match the updated release cycle page - https://www.ubuntu.com/about/release-cycle

---
*Reported from: https://www.ubuntu.com/server*

**Comment by SirSamTumless** [comment]
[
<img width="884" alt="Screenshot 2019-04-29 at 16 08 11" src="https://user-images.githubusercontent.com/28983816/56906447-259c0300-6a9a-11e9-8c5d-89a5bae6a213.png">
](url)

**Comment by SirSamTumless** [comment]
The graph on [/server](https://www.ubuntu.com/server) under "A release schedule you can depend"
![image](https://user-images.githubusercontent.com/28983816/56907013-529ce580-6a9b-11e9-8140-be5871fabc55.png) need to match the graph on https://www.ubuntu.com/about/release-cycle under the "Long term support and interim releases"
<img width="860" alt="Screenshot 2019-04-29 at 16 20 34" src="https://user-images.githubusercontent.com/28983816/56907117-86780b00-6a9b-11e9-85c8-29f993cd1c41.png">

**Comment by solazio** [comment]
@pmahnke am i supposed to use an image or a table for the schedule? Currently on [/server](https://www.ubuntu.com/server) we have an image and on[/about/release-cycle](https://www.ubuntu.com/about/release-cycle) we have a table.
