### ISSUE TITLE
X-Hostname header

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/www.ubuntu.com#5067]
Hello, Sander Bos has reported that some of our internal kubernetes names are visible externally:

$ curl -Is 'https://www.ubuntu.com/' | grep 'X-Hostname'
X-Hostname: juju-prod45-ubuntu-website-machine-18

This appears to be set here:

https://github.com/canonical-web-and-design/www.ubuntu.com/blob/cae74f5fc51029fa149e3c4361b37eec5642ece2/webapp/settings.py#L43

Is this intentional? Is this okay?

Thanks

**Comment by nottrobin** [comment]
This is intentional.

Do you know of a specific problem with this practice? We could of course remove it if there's a good reason.

**Comment by setharnold** [comment]
Sometimes leaking internal details of a network or infrastructure can provide extra attack reconnaissance -- so it's nice to make sure that these details still provide value for debugging or metrics periodically.

If you're happy then I'm happy.

Thanks
