### ISSUE TITLE
Update UA datasheet link

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/www.ubuntu.com#5078]
Please update the UA Datasheet CTA link with the web version of the Ubuntu Advantage Infrastructure datasheet.

@cristinadresch @SirSamTumless Wayne will need to create a web version of this datasheet

---
*Reported from: https://www.ubuntu.com/support*

**Comment by SirSamTumless** [comment]
@Khutch25 [This](https://drive.google.com/file/d/1Ip22Yv2MGaV4Fss85JxCCJe_etGZGJ1H/view?usp=sharing) datasheet you shared should be fine for the web.

**Comment by anasereijo** [comment]
That PDF needs to be uploaded to [assets site](https://manager.assets.ubuntu.com/) and the link copied

**Comment by Khutch25** [comment]
> @Khutch25 [This](https://drive.google.com/file/d/1Ip22Yv2MGaV4Fss85JxCCJe_etGZGJ1H/view?usp=sharing) datasheet you shared should be fine for the web.

@SirSamTumless The datasheet was finalised for print and has the crop marks on it, need a new version for web, unfortunately.
