### ISSUE TITLE
UASD issues

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/www.ubuntu.com#5096]
Ubuntu Advantage for Infrastructure (UA-I)
- [x] UA-I LEVEL table header looks weird. Looks like "ESSENTIAL", "UA-I LEVEL STANDARD", "ADVANCED

Support Services Process
- [x] 1  is mis-aligned.
- [ ] "Table of machines under support" doesn't completely make sense to me, and the table header existing seems to not be consistent with the rest of the page
- [x] 1.1 is repeated above and below table

Support Levels
- [x] "Support for guest instances other than Cluster." - I assume this should be "Cloud Guests" like it links to?
- [x] [http://www.ubuntu.com/certification/](http://www.ubuntu.com/certification/ The 

Managed Services
- [ ] The final point of 4 doesn't have a number, I believe this should be 4.6

Virtual Machines and Cloud Instances
- [ ] I don't think that the "Note" for number 3 should be its own bullet point.

---
*Reported from: https://www.ubuntu.com/legal/ubuntu-advantage-service-description

**Comment by pmahnke** [comment]
@cjohnston1158 
> "Table of machines under support" doesn't completely make sense to me, and the table header existing seems to not be consistent with the rest of the page

I removed the heading, but will as Stephan about the table

> The final point of 4 doesn't have a number, I believe this should be 4.6

asking Stephan

>  I don't think that the "Note" for number 3 should be its own bullet point.

asking Stephan
