### ISSUE TITLE
"Learn how to make a snap" link

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/www.ubuntu.com#5100]
@neimeyer pointed out that the "Learn how to make a snap" on https://www.ubuntu.com/internet-of-things link goes to an unnatural place (https://snapcraft.io homepage). We should consider where this should point to.

---
*Reported from: https://www.ubuntu.com/internet-of-things*

**Comment by pmahnke** [comment]
how about https://snapcraft.io/first-snap
