### ISSUE TITLE
/download/cloud - match cards styles

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/www.ubuntu.com#5105]
@pmahnke @anthonydillon, I don't know who designed or built this but do you know if there is a reason why the top 3 cards are `highlighted` and the bottom ones are not?
I suggest making them all the same style as it looks odd now.

## How it looks like

<img width="1090" alt="Screenshot 2019-05-07 at 14 59 58" src="https://user-images.githubusercontent.com/36884067/57310890-86eb5400-70e2-11e9-847c-e3d9cde8ec05.png">

## How it should look like

<img width="1099" alt="Screenshot 2019-05-07 at 15 02 48" src="https://user-images.githubusercontent.com/36884067/57310967-a97d6d00-70e2-11e9-91fd-d204df96cfad.png">

---
*Reported from: https://www.ubuntu.com/download/cloud*

**Comment by pmahnke** [comment]
@anasereijo just that the top three are way more important than the bottom three, can updated design as you wish.

**Comment by pmahnke** [comment]
for now, remove the highlight
