### ISSUE TITLE
/blog integration: Add navigation

### ISSUE THREAD

**Issue by b-m-f** [canonical-web-and-design/www.ubuntu.com#5121]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Add the blog navigation to get to the different groups.
**Dropdowns** on the navigation to select the categories are no longer needed when we integrate the filtering on the pages
## Screenshot

u.c/Screenshot%20from%202019-05-09%2013-51-39.png
![image](https://user-images.githubusercontent.com/2843450/57456033-782caa80-7264-11e9-97a1-320931c89ac9.png)

**Comment by anasereijo** [comment]
blog homepage should look like this:
https://github.com/canonical-web-and-design/web-squad/issues/974

**Comment by solazio** [comment]
Closed via https://github.com/canonical-web-and-design/www.ubuntu.com/pull/5144
