### ISSUE TITLE
[Takeover + landing] Starting with AI - Build

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/www.ubuntu.com#5133]
[brief](https://docs.google.com/document/d/1Wk1cowPs55rhNhbFCMPeSP-ynoxVP4hfH7ICg0T9X0E/edit#heading=h.gjdgxs)

**Comment by kwm14** [comment]
## Takeover assets
@solazio find build assets below for takeover 👍 

- Design discussion can be found [here](https://github.com/canonical-web-and-design/web-squad/issues/1134)
- Copy doc can be found [here](https://docs.google.com/document/d/1wc1YEeCDYplEv0HKJz59jGuh-OZ8tJoQ6cbJKKVk9tc/edit) [Option 2]
- Illustration - https://assets.ubuntu.com/v1/9f3f2b68-dotted-circle.svg
- Gradient - `background-image: linear-gradient(0deg, #48929B 0%, #2B585D 100%);`
- Suru fold - https://assets.ubuntu.com/v1/42b254a6-suru-fold.svg

### Visual
![AI-whitepaper-desktop](https://user-images.githubusercontent.com/17748020/57693410-09bf6200-7641-11e9-84c3-9c9ddaa899be.png)

![AI-whitepaper-mobile](https://user-images.githubusercontent.com/17748020/57693411-0a57f880-7641-11e9-9fce-4c7246628b63.jpg)

**Comment by kwm14** [comment]
## Landing page assets
@solazio find build assets below for landing page 👍 

- Copy doc can be found [here](https://docs.google.com/document/d/1oC74jvhUvWudAG4dQ7TluAQlY6DiM_b28_tDvL_ue-Q/edit#)
- Gradient- Same as above 😉 
- Illustration - https://assets.ubuntu.com/v1/b497ea41-get-started-illustration.svg

### Visual
![AI-whitepaper-landing](https://user-images.githubusercontent.com/17748020/57695084-40977700-7645-11e9-8fe7-c694c0fd427e.png)

**Comment by anasereijo** [comment]
@solazio is this in progress?

**Comment by solazio** [comment]
@anasereijo yes, it is built. Was waiting for some information from marketing which was added yesterday, however I didn't get any notification. We need to improve this type of communication in the future. Will make the changes now and create a PR. Thanks for asking!

**Comment by SirSamTumless** [comment]
This is good to go-live with the following whitepaper: 
[Getting Started With AI_WP_30.05.19 No ATOS.pdf](https://github.com/canonical-web-and-design/www.ubuntu.com/files/3240753/Getting.Started.With.AI_WP_30.05.19.No.ATOS.pdf)

Please, could we get this and the 451 webinar live on the site today?

**Comment by anasereijo** [comment]
@solazio please upload the pdf into [assets site](https://manager.assets.ubuntu.com/)

**Comment by SirSamTumless** [comment]
Also, something to note; don't call the uploaded PDF "Getting Started With AI_WP_30.05.19 No ATOS" but rather something like "Getting Started With AI_WP_30.05.19"
