### ISSUE TITLE
/server/hyperscale - Logos feed isn't working 

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/www.ubuntu.com#5138]
logos aren't showing on "A SELECTION OF OUR SOFTWARE PARTNERS" section:

<img width="1173" alt="Screenshot 2019-05-13 at 14 24 08" src="https://user-images.githubusercontent.com/36884067/57624911-caced500-758a-11e9-9b7b-e51b8474b402.png">

---
*Reported from: https://www.ubuntu.com/server/hyperscale*

**Comment by anasereijo** [comment]
@solazio please estimate this

**Comment by solazio** [comment]
@anasereijo what browser were you using? I checked google chrome and FF and it works fine.

**Comment by anasereijo** [comment]
@solazio chrome too

**Comment by solazio** [comment]
@anasereijo you are right. It is supposed to display openstack partners from this url [http://partners.ubuntu.com/partners.json?programme__name=OpenStack&service-offered=softwarecontent-publisher](http://partners.ubuntu.com/partners.json?programme__name=OpenStack&service-offered=softwarecontent-publisher) but thre are no such partners.
@pmahnke can we display these software partners from [https://partners.ubuntu.com/programmes/software](https://partners.ubuntu.com/programmes/software)
![image](https://user-images.githubusercontent.com/40214246/57677868-c6a0c700-761f-11e9-8df9-84a5f52412ac.png)

**Comment by pmahnke** [comment]
@anasereijo and @solazio can you just remove BOTH logo cloud sections?  we might add them back later, but these programmes are in flux
