### ISSUE TITLE
Feed failed to load

### ISSUE THREAD

**Issue by waynecrosby** [canonical-web-and-design/www.ubuntu.com#5139]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

[please describe the issue]

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by anasereijo** [comment]
This should be fixed now
