### ISSUE TITLE
The pagination dots are not in the middle as they are supposed to be

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/www.ubuntu.com#5148]
This is an issue for [upgrade-to-django2](https://github.com/canonical-web-and-design/www.ubuntu.com/tree/upgrade-to-django2) branch

## Summary

The pagination dots are not in the middle as they are supposed to be

## Process

On upgrade-to-django2 branch, go to [/blog/internet-of-things](http://0.0.0.0:8001/blog/internet-of-things) and scroll down to the pagination

On upgrade-to-django2 branch, go to [/blog/archives page](http://0.0.0.0:8001/blog/archives) and check the position of the dots on the right side of the page

## Current and expected result

The pagination dots are not in the middle as they are supposed to be

## Screenshot

![image](https://user-images.githubusercontent.com/40214246/57771636-29bb5800-770b-11e9-8353-560af3b137cb.png)

**Comment by anasereijo** [comment]
@solazio should this be in Blog epic?
