### ISSUE TITLE
Pagination doesn't persist existing URL query params

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/www.ubuntu.com#5161]
## Summary

When filtering blog archives by one or all of `year`, `month` and `group`, if the results are spread across multiple pages, all filters are lost when navigating via pagination.

## Process

- Check out `upgrade-to-django2` branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/blog/archives](http://0.0.0.0:8001/blog/archives)
- Filter by the year `2018` in the right-hand list of Archive links 
- Click any pagination link

## Current and expected result

**Current:** when the page loads, the URL no longer contains a `year` parameter, and there are results from 2019.

**Expected:** when the page loads, I should see a second page of 2018 results.

**Comment by pmahnke** [comment]
Issue moved to [canonical-web-and-design/canonicalwebteam.blog #58](https://github.com/canonical-web-and-design/canonicalwebteam.blog/issues/58) via [**ZenHub**](https://www.zenhub.com/)
