### ISSUE TITLE
/blog: Implement upcoming events and webinars on homepage

### ISSUE THREAD

**Issue by b-m-f** [canonical-web-and-design/www.ubuntu.com#5166]
# Summary

Blog module **1.5.12** adds the next 3 upcoming *events* and *webinars* to the homepage
These should be included into the `blog/index,html` template so that it looks like https://blog.ubuntu.com

![image](https://user-images.githubusercontent.com/2843450/57923849-6453fa80-789b-11e9-8bad-1b5762a732f3.png)

**Comment by anasereijo** [comment]
please estimate
