### ISSUE TITLE
/download/desktop/thank-you - padding reCAPTCHA to be fixed

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/www.ubuntu.com#5178]
padding-right on the reCAPTCHA iframe to match newsletter card

![Thank you for your contribution   Ubuntu](https://user-images.githubusercontent.com/36884067/58097549-98972600-7bcf-11e9-8a11-1157d3223fb8.png)

---
*Reported from: https://www.ubuntu.com/download/desktop/thank-you*

**Comment by anasereijo** [comment]
@dev please estimate this issue

**Comment by sowasred2012** [comment]
closing this issue - recaptcha isn't responsive, it sits inside an iframe containing fixed width elements. An alternative would be to use the `data-size="compact"` option, but it looks terrible.

**Comment by anasereijo** [comment]
@sowasred2012 can you please estimate this? thanks
