### ISSUE TITLE
/security change link on strip to be inverted link

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/www.ubuntu.com#5179]
make the "Watch the Ubuntu security webinar" link `inverted`

<img width="1440" alt="Screenshot 2019-05-15 at 10 37 25" src="https://user-images.githubusercontent.com/36884067/58102197-ca60ba80-7bd8-11e9-805b-0aed0a99e9a9.png">

---
*Reported from: https://www.ubuntu.com/security*

**Comment by solazio** [comment]
closing as it is not relevant anymore

![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/7c34c3c4-743c-4746-92ff-0e5365293f2f)
