### ISSUE TITLE
The language in releases.ubuntu.com doesn't make any reference to modern processors

### ISSUE THREAD

**Issue by frio** [canonical-web-and-design/www.ubuntu.com#5206]
Steps to Reproduce:

1. Intend to download and install Ubuntu
2. Visit http://releases.ubuntu.com/19.04/
3. Try and find a download that works for my processor

Expected Results:

Some language about the processors each release works on (eg. Core i3, i5, i7, AMD Ryzen).

Actual Results:

Most recent Intel processor referenced is the Core 2.

Notes:

For people who aren't aware that amd64 means x86-64, this is confusing; it appears that Ubuntu only supports AMD machines or very old Intels.  Just updating the names of the processors the architecture works for to include the modern Core spins would probably suffice.

I'd open a PR with the change, but it doesn't seem like `releases.ubuntu.com` gets spun out of this repo (or I'm just blind); conversely, I can't find any other obvious buttons for raising a bug.

---
*Reported from: https://www.ubuntu.com/*

**Comment by anthonydillon** [comment]
Thank you for the suggestion. This is the bug list for www.ubuntu.com issues. Please file this issue with the team that maintain the releases website: https://bugs.launchpad.net/ubuntu-cdimage/+filebug
