### ISSUE TITLE
/blog: Design topics dropdown

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/www.ubuntu.com#5211]

**Comment by anasereijo** [comment]
notes to self:
use vanilla's [contextual menu ](https://docs.vanillaframework.io/en/patterns/contextual-menu)
ask to add secondary navigation on topics pages
ask to add Topics link on secondary nav

**Comment by anasereijo** [comment]
@clagom see below the dropdown solution as discussed last week. Just wanted to double check with you if still makes sense?
Spencer and I thought that might be better to keep the current vanilla pattern ([contextual menu](https://docs.vanillaframework.io/en/patterns/contextual-menu)) as we will soon have a new dropdown and then we can relook at this.


![sec colour blue](https://user-images.githubusercontent.com/36884067/58791987-2ff67300-85eb-11e9-8842-65f12599ff96.jpg)

**Comment by clagom** [comment]
I think it works well @anasereijo, then with the new pattern from Vanilla we can sync up later on.
