### ISSUE TITLE
Update the takeover rotation

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/www.ubuntu.com#5236]
Please change the current takeovers to the following as per [this sheet](https://docs.google.com/spreadsheets/d/1MaFd-ZHWpRVjIP9Sj_dOCIGOtl-GJYbrXewt5EG4m80/edit?ts=5cc05f70#gid=564832475):
- 451 Automotive
 - AI consulting
- Ubuntu 19.04 webinar

**Comment by anasereijo** [comment]
I guess this needs to be done asap?

**Comment by solazio** [comment]
@anasereijo & @SirSamTumless we already have these live: 
- 451 Automotive
- AI consulting
- Ubuntu 19.04 webinar
