### ISSUE TITLE
[Whitepaper + takeover + landing] Starting with AI - rebuild

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/www.ubuntu.com#5241]
# Update the AI Whitepaper + takeover + landing.

- [ ] The metadata needs to be created so that when shared on social, text and images pull through.

- [ ] The takeover text should be re-written to align with the current TOV.

- [ ] Design changes as per Ana's changes.

**Comment by anasereijo** [comment]
new design [here](https://github.com/canonical-web-and-design/web-squad/issues/1215). Only [changed the illustration](https://assets.ubuntu.com/v1/5fc06110-AI+illustration.svg), the background stays the same.
