### ISSUE TITLE
[Copy Update] kubernetes - "Kubernetes" - jaas.ai

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/www.ubuntu.com#5249]
Please update kubernetes - "Kubernetes" - jaas.ai from the [copy doc](https://docs.google.com/document/d/1LXZM3RpFoIhInfdQI0Go7xL9hxCGcit1HVoncvm1cok/edit?usp=drivesdk)

**Comment by SirSamTumless** [comment]
@WendyS1000 I have assigned you to this to review the changes that were made by Kelly.

**Comment by pmahnke** [comment]
Issue moved to [canonical-web-and-design/jaas.ai #313](https://github.com/canonical-web-and-design/jaas.ai/issues/313) via [**ZenHub**](https://www.zenhub.com/)

**Comment by pmahnke** [comment]
Issue moved to [canonical-web-and-design/jaas.ai #314](https://github.com/canonical-web-and-design/jaas.ai/issues/314) via [**ZenHub**](https://www.zenhub.com/)
