### ISSUE TITLE
Uncaught reference error in console on several pages

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/www.ubuntu.com#5275]
## Summary
On the following pages there is an error in the console that reads:

```
Uncaught ReferenceError: $ is not defined
```

- https://www.ubuntu.com/engage/evolving-software
- https://www.ubuntu.com/engage/hiri-case-study
- https://www.ubuntu.com/engage/cloud-init-whitepaper
- https://www.ubuntu.com/engage/kernel-telco-nfv
- https://www.ubuntu.com/engage/fingbox-case-study
- https://www.ubuntu.com/engage/northstar

## Process

Go to any of the pages listed above and check the console in the browsers developer tools. You should see the error.

## Current and expected result

There should be no javascript errors in the console

**Comment by pmahnke** [comment]
Dup of #5271
