### ISSUE TITLE
Landscape link

### ISSUE THREAD

**Issue by waynecrosby** [canonical-web-and-design/www.ubuntu.com#5282]
Can the 'Learn about Landscape ›' link in the page anchor link to the relevant section on the UA page it links to or alternatively link directly to the Landscape website?
As it is we are asking a lot of the user to find the information they are clicking to.
<img width="401" alt="Screenshot 2019-06-07 at 11 48 48" src="https://user-images.githubusercontent.com/42238722/59099332-b4623200-891a-11e9-8cfc-f812bf677d0e.png">

---
*Reported from: https://www.ubuntu.com/server/thank-you*

**Comment by anasereijo** [comment]
Hey Wayne, thanks for filling this issue!

I just checked the [copy doc](https://docs.google.com/document/d/1XWmMQlhgqHeDrMepfxDzeDvXSwTMUbXW8s78bBOsfDw/edit) and it's linking to the [/pricing](https://www.ubuntu.com/pricing) page. The Ubuntu Advantage section is also linking to the same page. The copy isn't matching either so I left comments. Hopefully this will be fixed soon

thanks
